### ISSUE TITLE
Question - where i launch the command with the prefix [p] ? 

### ISSUE THREAD

**Issue by p4535992** [arconyx/Athena-Cogs#13]
Hi sorry to bother, just started using discord bot, i have installed the Red Discord Bot and everything, now i can see the bot on my channel, but i cannot understand where i must launch the commands on the general paragraph like this:

`[p]load downloader`

Can you give more indications about this ?
ty in advance.

**Comment by arconyx** [comment]
Oh dear, I managed to forget this was here for almost a year. I doubt you're still trying (sorry!), but I'll answer for the record.

While setting up the bot you will have had the option to choose a prefix. I use `!` for example. This should be displayed in an infobox in the console when the bot launches. To run a command you replace `[p]` with your prefix so `[p]load downloader` becomes `!load downloader`.
