### ISSUE TITLE
New Kanka Entity "Creatures"

### ISSUE THREAD

**Issue by grutschm** [arconyx/Athena-Cogs#14]
_Hi. First of all, thanks for this cog, it works really well for our Westmarches DnD Campaign where we use Discord and Kanka! The setup was also straight forward and pretty easy. Good job and thanks again!_

**ISSUE**
Kanka recently added "Creatures" to their portfolio of entities. Naturally the cog would need some adjustments to incorporate those.

**Comment by arconyx** [comment]
That should do it. You can update with `!cog update kankaview`, substituting in the appropriate prefix for your bot. Reload the cog when prompted. Let me know if there are any problems.

**Comment by grutschm** [comment]
Wow, that was really fast, works like a charm, thanks a lot!
